### ISSUE TITLE
v1.3.0 doesn't exist

### ISSUE THREAD

**Issue by baldhead69** [Microchip-MPLAB-Harmony/harmony-services#1]
Hi,

I tried to download by command line "harmony-services" using "git clone --depth 1 --branch v1.3.0 https://github.com/Microchip-MPLAB-Harmony/harmony-services", but v1.3.0 doesnot exist in github (maybe in another place).

In mcc appear the v1.3.0 version option to download (  but mcc is buggy and not working properly ).

I installed the version v1.2.0 for now.

`
C:\microchip\mplab-harmony>git clone --depth 1 --branch v1.3.0 https://github.com/Microchip-MPLAB-Harmony/harmony-services

Cloning into 'harmony-services'...

warning: Could not find remote branch v1.3.0 to clone.

fatal: Remote branch v1.3.0 not found in upstream origin
`

I also tried to download by command line FreeRTOS using "git clone --depth 1 --branch v10.5.1 https://github.com/Microchip-MPLAB-Harmony/CMSIS-FreeRTOS", but v10.5.1 not exist in github(maybe in another place).

On github, i haven't found an option to open an issue about this ( "https://github.com/Microchip-MPLAB-Harmony/CMSIS-FreeRTOS" ).

In mcc appear the v10.5.1 version option to download ( but mcc is buggy and not working properly ).

I installed the version v10.4.6 for now.

**Comment by aethaniel** [comment]
Hi @baldhead69, thanks for your issue report and sorry for being late replying to you.
I can already answer about Harmony Services v1.3.0: we never did any release of this tag, even internally. So, I don't understand why you are looking for it. We published recently Harmony Services v1.2.1 for few bug fixes.

Regarding FreeRTOS, I will update the catalogs soon following some spring cleanup and the original repository will be in use instead of our mirror (which will be removed).

For your information: https://github.com/Microchip-MPLAB-Harmony/catalog.

In term of deployment, https://github.com/Microchip-MPLAB-Harmony/contentmanager is still active for the moment, even if the strategy is to use ultimately only the new MCC Content Manager. Harmony Content Manager takes care of downloading the dependencies when needed. MCC CM will have this feature implemented in some weeks.

**Comment by baldhead69** [comment]
Hi @aethaniel 

After i updated the mcc,  apparently everything is solved.

I deleted my "harmony folder" too, and let mcc download everything again.

Thank's.
